version: '3.2'

volumes:
  data:
services:

  application:
    container_name: php_laravel
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    privileged: true
    networks:
      rede:
        ipv4_address: 14.0.0.10
    ports:
      - 8014:80
    links:
      - mysqldb
    volumes:
      - type: bind
        source: ./
        target: /var/www/html

  mysqldb:
    container_name: database_php_laravel
    image: mysql:8.0.20
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    privileged: true
    networks:
      rede:
        ipv4_address: 14.0.0.11
    ports:
      - 3314:3306
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: QAZasd1
      MYSQL_DATABASE: laravel_produtos

networks:
  rede:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 14.0.0.1/24


